statement ::= declaration parameterization? "=" expression ";"

expression ::= compound_expression
             | enum_list
             | identifier application?

parameter ::= label ":" type | type
declaration ::= label ":" type | label

type ::= identifier
       | identifier refinement

refinement ::= "[" refinement_list "]"
refinement_list ::= expression_list // that must typecheck to bool


compound_expression ::= "{" statement_list "}"
statement_list ::= statement*

parameterization ::= "(" parameter_list ")"
parameter_list ::= parameter ("," parameter)*

application ::= "(" expression_list ")"
expression_list ::= expression ("," expression)*

enum_list ::= ("|" label)+

identifier ::= label ("." label)*

label ::= // Any string of letters
